version: "2"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
  web:
    container_name: rails
    build: docker/rails
    command: bundle exec rails s -p 3000
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: "root"
      DATABASE_URL: 'mysql2://root:root@mysql:3306'
    depends_on:
      - mysql
    volumes:
      - ./:/myapp
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.6.32
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
