version: "2"
services:
  # proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  datastore:
    image: busybox
    volumes:
      - /share
      - ./docker/mysql/volumes:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes_from:
      - datastore
    depends_on:
      - datastore
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    container_name: rails
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    extends:
      file: ./docker/mysql/password.yml
      service: password
    depends_on:
      - db
  db:
    image: mysql:5.7.17
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
    depends_on:
      - datastore
    extends:
      file: ./docker/mysql/password.yml
      service: password
