# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca2ad459c91ce4f93a2e19d3e6e3801c3556ebf2104d91979e5a295aa10f4e809f95e582cb658555a8705da415209114f1334cc4a4cebd9296cd624ede824ca1

test:
  secret_key_base: 1b94d5aa7ade63d09a3f68a3cc4734440f5a73b607a522949af71bc77c1d2f23789d75759bacb0ecdfe5d543a656eba5ec63ad2b0d357dc882dcaf1a7fa554ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
